name: Format
on:
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Format
        run: |
          npm ci
          npx prettier --write .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
